version: "2.1"

services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - AUTO_UPDATE=true
    volumes:
      - /var/lib/seedbox/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /var/lib/seedbox/sonarr:/config
      - /var/lib/seedbox/library:/content
      - /var/lib/seedbox/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /var/lib/seedbox/radarr:/config
      - /var/lib/seedbox/library:/content
      - /var/lib/seedbox/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  default:
