version: '3.4'

services: 
  vpn:
    image: dperson/openvpn-client
    container_name: seedbox-vpn
    cap_add:
      - net_admin
    environment:
      - TZ=EST5EDT
      - DNS=8.8.8.8
    networks:
      - default
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /etc/seedbox/vpn:/vpn
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: seedbox-qbittorrent
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=EST5EDT
      - WEBUI_PORT=8080
    network_mode: "service:vpn"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /var/lib/seedbox/downloads:/downloads
      - /var/lib/seedbox/qbittorrent:/config

networks:
  default: